# Generated by Django 3.1.1 on 2020-09-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_firstvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
