# Generated by Django 3.1.1 on 2020-09-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200905_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentViewCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentViewCheck1',
        ),
    ]
